#! /bin/sh

ID="${1}"
if [ -z "$ID" ]; then
   ID=$(sudo kata-runtime list -q)
fi

CONSOLE="/run/vc/vm/$ID/console.sock"

if [ -z "$ID" ]; then
    CONSOLE=$(find /run/vc/vm -name "console.sock")
fi

sudo socat stdin,raw,echo=0,escape=0x11 unix-connect:"${CONSOLE}"
